"""
Django settings for _03_django_orm project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pl0=#5hlja4@bllqu(2b)av3wa%3a-pjsp5ap4)v99&5954sv&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'post',
    'product',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_03_django_orm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_03_django_orm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ORM 사용할 데이터베이스 설정
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL 데이터베이스 엔진
        'NAME': 'djangodb',      # 사용할 데이터베이스
        'USER' : 'django',       # DB 접속 계정
        'PASSWORD' : 'django',   # DB 접속 비밀번호
        'HOST' : '127.0.0.1',    # DB 서버 주소
        'PORT' : '3306',         # MySQL 포트 번호
        'OPTIONS' : {
            'charset': 'utf8mb4',  # 문자 인코딩 (한글/이모지 저장시 깨지지 않도록 설정)
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ORM 쿼리 로그 출력 형식 지정
import sqlparse  # SQL 쿼리를 조작

# SQL 로그를 보기 좋게 포맷팅하는 클래스
class SQLFormatter:
    def format(self, record):
        if record.sql:  # SQL 로그이면
            # SQL 키워드는 대문자로, 들여쓰기 적용
            formatted_sql = sqlparse.format(record.sql, reindent=True, keyword_case='upper')
            execution_time = getattr(record, 'duration', 0.0)  # record에 duration 속성이 있으면 사용, 없으면 0.0
            return f"{formatted_sql}\n[Execution Time: {execution_time:.3f} ms]"
        return record.getMessage()  # 일반 로그 메시지면 메시지 그대로 반환

# 로그 설정
LOGGING = {
    'version': 1,  # 로깅 설정 버전
    'disable_existing_loggers': False,  # 기존 로거 비활성화 여부
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',  # 콘솔에 로그 출력
            'formatter': 'custom_sql',         # 포맷터 설정
        },
    },
    'formatters': {
        'custom_sql': {
            '()': SQLFormatter,  # 사용자 정의 포맷터 클래스 등록
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',         # DB 쿼리 로그는 DEBUG 레벨로 출력
            'handlers': ['console'],  # console 핸들러 사용
        },
    },
}